name: Rust CI

# Se ejecutará al hacer push a la rama principal
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar caché de Cargo (Acelera la compilación)
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Verificar que el código compila
      run: cargo check --verbose

    - name: Ejecutar pruebas matemáticas
      run: cargo test --verbose
